#!/bin/bash
echo "Reseting lokal Repo and fetching + pull all content from origin/main"

echo "Check out local master branch"
git checkout master

echo "fetch origin to get all changes from the remote repo
git fetch origin

echo "reset all local changes that are untracked or no pushed to origin"
git reset --hard origin/main

