#!/bin/bash
echo "Reseting lokal Repo and fetching + pull all content from origin/main Also creating a new feature branch and inititaly pushing to origin"

# "changing to parent directory since we are loaded as a subrepo =)"
cd ..

# "Check out local master branch"
git checkout master

# "fetch origin to get all changes from the remote repo"
git fetch origin

# "reset all local changes that are untracked or no pushed to origin"
git reset --hard origin/master

# "also deleting untracked files"
git clean -f

# "switching to feature branch"
git switch -c new_feature_branch 
git push -u origin new_feature_branch
