#!/bin/bash
echo "All changes are done. Only the commit and push + merge request is needed now"

# "changing to parent directory since we are loaded as a subrepo =)"
cd ..

# Adding all changed files
git add .

# Calling commit without -m so that she needs to enter the commit Message in the editor
git commit

# now pushing changes towards the origin feature branch
git push


# opening browser with the pull request URL
# Open the browser (replace 'brave-browser' with your browser command)
brave-browser https://gitlab.com/SaschaCode/koerperuseele/-/merge_requests/new?merge_request%5Bsource_branch%5D=new_feature_branch &

# Wait for the browser to close
wait $!