#!/bin/bash
echo "Cleaning up. Therefor deleting local and remote branch"

# "Switch to master first"
git switch master

# "fetch origin to get all changes from the remote repo"
git branch -D new_feature_branch

# "After that we gonne also delete the remote branch"
# We'll delete the online branch after the merge is completed automatically 
# git push origin --delete new_feature_branch